import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import Title from '../components/Title';
import NavBar from '../components/NavBar';


export default function Home() {
  const [boxSprite, setBoxSprite]: any = useState(null);
  
  let random = (Math.floor(Math.random() * 151) + 1).toString();

  useEffect(() => {
    fetch(`https://pokeapi.co/api/v2/pokemon/${random}`)
      .then((res) => res.json())
      .then((data) => {
        setBoxSprite(data);
      })
  }, []);

  //placeholder
  if (boxSprite === null) {
    return (
    <>
    <Head>
          <title>Pokemon Store</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <header>
          <Title />
        </header>

        <nav>
          <NavBar />
        </nav>

        <main className='homeMain'>
          <div className='boxWrapper'>

            <Link href='/Navigation' className='boxLink'><div className='box' id='boxOne'>
              <p>See All Pokemon</p>
              <img></img>
            </div></Link>
            <div className='box'>-</div>
            <div className='box'>-</div>
            <div className='box'>-</div>
            <div className='box'>-</div>
            <div className='box'>-</div>
            <div className='box'>-</div>
            <div className='box'>-</div>

          </div>

        </main>
    </>
    )
  } else {
    //right return
    return (
      <>
        <Head>
          <title>Pokemon Store</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>

        <header>
          <Title />
        </header>

        <nav>
          <NavBar />
        </nav>

        <main className='homeMain'>
          <div className='boxWrapper'>

            <Link href='/Navigation' className='boxLink'><div className='box' id='boxOne'>
              <p>See All Pokemon</p>
              <img src={boxSprite.sprites.other['official-artwork'].front_default}></img>
            </div></Link>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>
            <div className='box'>Soon</div>

          </div>

        </main>
      </>
    )
  }
}
